version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  ignore:
    - dependency-name: "cryptography"
      versions: ["39.0.0"]  # https://github.com/whitphx/streamlit-webrtc/issues/1164
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/streamlit_webrtc/frontend"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: "daily"
